CREATE TABLE inventory (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(255) NOT NULL,
    available    INTEGER      NOT NULL
);

CREATE TABLE order_inventory (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id   INTEGER      NOT NULL REFERENCES inventory (id),
    order_id       VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255) NOT NULL,
    order_quantity INTEGER      NOT NULL,
    old_quantity   INTEGER      NOT NULL,
    new_quantity   INTEGER      NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL
);
