CREATE TABLE product (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL
);

CREATE TABLE validation (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255) NOT NULL,
    success        BOOLEAN      NOT NULL,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL
);
