CREATE TABLE payment (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       VARCHAR(255)     NOT NULL,
    transaction_id VARCHAR(255)     NOT NULL,
    total_items    INTEGER          NOT NULL,
    total_amount   DOUBLE PRECISION NOT NULL,
    status         VARCHAR(255)     NOT NULL,
    created_at     TIMESTAMP(6)     NOT NULL,
    updated_at     TIMESTAMP(6)     NOT NULL
);
